(function() {var implementors = {};
implementors["yup_oauth2"] = ["impl <a class='trait' href='hyper/header/common/authorization/trait.Scheme.html' title='hyper::header::common::authorization::Scheme'>Scheme</a> for <a class='struct' href='yup_oauth2/struct.Scheme.html' title='yup_oauth2::Scheme'>Scheme</a>",];implementors["google_tasks1"] = ["impl <a class='trait' href='hyper/header/common/authorization/trait.Scheme.html' title='hyper::header::common::authorization::Scheme'>Scheme</a> for <a class='struct' href='yup_oauth2/types/struct.Scheme.html' title='yup_oauth2::types::Scheme'>Scheme</a>",];implementors["google_proximitybeacon1_beta1"] = ["impl <a class='trait' href='hyper/header/common/authorization/trait.Scheme.html' title='hyper::header::common::authorization::Scheme'>Scheme</a> for <a class='struct' href='yup_oauth2/types/struct.Scheme.html' title='yup_oauth2::types::Scheme'>Scheme</a>",];implementors["google_blogger3"] = ["impl <a class='trait' href='hyper/header/common/authorization/trait.Scheme.html' title='hyper::header::common::authorization::Scheme'>Scheme</a> for <a class='struct' href='yup_oauth2/types/struct.Scheme.html' title='yup_oauth2::types::Scheme'>Scheme</a>",];implementors["google_manager1_beta2"] = ["impl <a class='trait' href='hyper/header/common/authorization/trait.Scheme.html' title='hyper::header::common::authorization::Scheme'>Scheme</a> for <a class='struct' href='yup_oauth2/types/struct.Scheme.html' title='yup_oauth2::types::Scheme'>Scheme</a>",];implementors["google_groupsmigration1"] = ["impl <a class='trait' href='hyper/header/common/authorization/trait.Scheme.html' title='hyper::header::common::authorization::Scheme'>Scheme</a> for <a class='struct' href='yup_oauth2/types/struct.Scheme.html' title='yup_oauth2::types::Scheme'>Scheme</a>",];implementors["google_dfareporting2d1"] = ["impl <a class='trait' href='hyper/header/common/authorization/trait.Scheme.html' title='hyper::header::common::authorization::Scheme'>Scheme</a> for <a class='struct' href='yup_oauth2/types/struct.Scheme.html' title='yup_oauth2::types::Scheme'>Scheme</a>",];implementors["google_dfareporting2d2"] = ["impl <a class='trait' href='hyper/header/common/authorization/trait.Scheme.html' title='hyper::header::common::authorization::Scheme'>Scheme</a> for <a class='struct' href='yup_oauth2/types/struct.Scheme.html' title='yup_oauth2::types::Scheme'>Scheme</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
